#@ load("@ytt:data","data")
#@ load("@ytt:overlay","overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment"}),expects=1
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name":"external-dns"})
      - name: external-dns
        #@overlay/replace via=lambda left, right: left+":"+right
        image: v0.13.5