---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: external-dns.roles.grogscave.net.1.0.0
spec:
  refName: external-dns.roles.grogscave.net
  version: 1.0.0
  releaseNotes: |
        Initial release of the external-dns role
  includedSoftware:
  - displayName: external-dns
    version: v0.13.5
    description: External DNS
  valuesSchema:
    openAPIv3:
      title: external-dns.roles.grogscave.net.1.0.0 values schema
      examples:
      - namespace: external-dns
      properties:
        namespace:
          type: string
          default: external-dns
        provider:
          type: string
          default: aws
          enum:
          - aws
        domain:
          type: string
        owner_id:
          type: string
        aws:
          type: object
          properties:
            role_arn:
              type: string

  template:
    spec:
      fetch:
      - git:
          url: https://github.com/cdelashmutt-pivotal/demo-clusters
          ref: origin/main
          subPath: packages/external-dns
      template:
      - ytt:
          paths:
          - "upstream"
          - "overlays"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}