#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tap-pkgr
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: pkgr
spec:
  fetch:
    imgpkgBundle:
      image: #@ data.values.tap_install.package_repository.oci_repository
      tagSelection:
        semver:
          constraints: #@ data.values.tap_install.version.package_repo_bundle_tag
