#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
tap_install:
  version:
    package_repo_bundle_tag: "1.6.2"
    package_version: "1.6.2"
  package_repository:
    oci_repository: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages
  #@schema/type any=True
  values:
    excluded_packages:
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
      - fluxcd.source.controller.tanzu.vmware.com
    ceip_policy_disclosed: true
    shared:
      ingress_domain: "aws-work.grogscave.net"
      ingress_issuer: ""
      image_registry:
        project_path: "gcr.io/pa-cdelashmutt/cdd-demo-tap/supply-chain"
      kubernetes_version: "1.25.9"
    supply_chain: testing_scanning

    tap_telemetry:
      installed_for_vmware_internal_use: "true"

    appsso:
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
      default_workload_domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

    accelerator:
      ingress:
        include: true
        enable_tls: true
      tls:
        namespace: default
        secret_name: default-cert

    appliveview_connector:
      activateAppLiveViewSecureAccessControl: false
      activateSensitiveOperations: true

    cnrs:
      default_tls_secret: default/default-cert
      domain_template: "{{- .Name}}-{{.Namespace -}}.{{.Domain}}"
      ingress:
        external:
          namespace: tanzu-system-ingress
        internal:
          namespace: tanzu-system-ingress
    contour:
      contour:
        replicas: 2
      infrastructure_provider: aws
      envoy:
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: '*.aws-work.grogscave.net'
        workload:
          type: Deployment
          replicas: 2

    metadata_store:
      ns_for_export_app_cert: "*"
      app_service_type: ClusterIP
    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: namespace-provisioner/cdd-demo/namespaces
        url: https://github.com/cdelashmutt-pivotal/demo-clusters
      additional_sources:
        - git:
            ref: origin/main
            subPath: namespace-provisioner/cdd-demo/supplychain-resources
            url: https://github.com/cdelashmutt-pivotal/demo-clusters
          path: _ytt_lib/supplychain-resources
    package_overlays:
    - name: cert-manager
      secrets:
      - name: cert-manager-overlay
    - name: build-service
      secrets:
      - name: build-service-export-overlay