---
apiVersion: v1
kind: Secret
metadata:
  name: tap-gui-overlay
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.0: "upsert before upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete after deleting pkgi"
type: Opaque
stringData:
  overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "ServiceAccount", "metadata": {"name": "tap-gui"}})
    ---
    #@overlay/match missing_ok=True
    #@overlay/match-child-defaults missing_ok=True
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::537807987484:role/cdd-demo-tap-gui-tap-gui