#@ load("@ytt:data", "data")
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterissuers.cert-manager.io
  annotations:
    kapp.k14s.io/change-group: certmanager-crd
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule: "upsert after upserting pkgi"
spec:
  scope: Cluster
  group: cert-manager.io
  versions:
    - name: v1
  names:
    kind: ClusterIssuer
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certificates.cert-manager.io
  annotations:
    kapp.k14s.io/change-group: certmanager-crd
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule: "upsert after upserting pkgi"
spec:
  scope: Namespaced
  group: cert-manager.io
  versions:
    - name: v1
  names:
    kind: Certificate
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tlscertificatedelegations.projectcontour.io
  annotations:
    kapp.k14s.io/change-group: contour-crd
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule: "upsert after upserting pkgi"
spec:
  scope: Namespaced
  group: projectcontour.io
  versions:
    - name: v1
  names:
    kind: TLSCertificateDelegation
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-contour-cluster-issuer
  annotations:
    kapp.k14s.io/change-group: issuer
    kapp.k14s.io/change-rule.0: "upsert after upserting certmanager-crd"
    kapp.k14s.io/change-rule.1: "delete before deleting certmanager-crd"
spec:
  acme:
    email: cdelashmutt@vmware.com
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          region: us-east-2
          hostedZoneID: Z08415692IPTOH7IE83R
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-cert
  namespace: default
  annotations:
    kapp.k14s.io/change-group: cert
    kapp.k14s.io/change-rule.0: "upsert after upserting issuer"
    kapp.k14s.io/change-rule.1: "delete before deleting issuer"
spec:
  commonName: #@ "*.{}".format(data.values.tap_install.values.shared.ingress_domain)
  dnsNames:
  - #@ "*.{}".format(data.values.tap_install.values.shared.ingress_domain)
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: default-cert
  subject:
    organizations:
    - vmware
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: default-cert
  namespace: default
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting cert"
    kapp.k14s.io/change-rule.1: "delete before deleting cert"
spec:
  toNamespaces:
  - '*'
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: default-cert
  namespace: default
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting cert"
    kapp.k14s.io/change-rule.1: "delete before deleting cert"
    kapp.k14s.io/change-rule.2: "upsert after upserting contour-crd"
    kapp.k14s.io/change-rule.3: "delete before deleting contour-crd"
spec:
  delegations:
  - secretName: default-cert
    targetNamespaces:
    - "*"
