---
apiVersion: v1
kind: Secret
metadata:
  name: tap-values
  namespace: tanzu-continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: "tap-config"
    kapp.k14s.io/change-rule.0: "upsert before upserting tap"
    kapp.k14s.io/change-rule.1: "delete after deleting tap"
type: Opaque
stringData:
  values.yaml: |
    tap_install:
      version:
        package_repo_bundle_tag: "1.7.0"
        package_version: "1.7.0"
      values:
        shared:
          ingress_domain: "run.aws-work.grogscave.net"
          image_registry:
            project_path: "gcr.io/pa-cdelashmutt/cdd-demo-tap/supply-chain"
          kubernetes_version: "1.27"
        local_source_proxy:
          repository: gcr.io/pa-cdelashmutt/cdd-demo-tap/source
        contour:
          envoy:
            service:
              annotations:
                external-dns.alpha.kubernetes.io/hostname: '*.run.aws-work.grogscave.net'

    ootb_supply_chain_testing_scanning:
      gitops:
        server_address: https://github.com
        repository_owner: cdelashmutt-pivotal
        repository_name: cdd-demo-gitops
        commit_strategy: pull_request
        pull_request:
          server_kind: github
          commit_branch: supply_chain
          pull_request_title: Delivery from Supply Chain
          pull_request_body: This is a candidate release for promotion

    scanning:
      resources:
        limits:
          cpu: "500m"
          memory: 3Gi
        requests:
          cpu: 200m
          memory: 1Gi
          
    tap_gui:
      tls:
        namespace: default
        secretName: default-cert
      app_config:
        auth:
          environment: development
        customize:
          default_route: /home
        grafana:
          domain: https://grafana.run.aws-work.grogscave.net # URL of your Grafana domain
          unifiedAlerting: true
        catalog:
          locations:
            - type: url
              target: https://github.com/cdelashmutt-pivotal/demo-clusters-tap/blob/main/clusters/cdd-demo-aws/backstage-catalog/catalog-info.yaml
            - type: url
              target: https://github.com/tsalm-vmware/spring-cloud-demo-tap/blob/main/tap/catalog/catalog-info.yaml
            - type: url
              target: https://github.com/cdelashmutt-pivotal/java-rest-service/blob/main/catalog/catalog-info.yaml
            - type: url
              target: https://github.com/cdelashmutt-pivotal/weatherforecast-steeltoe/blob/main/catalog/catalog-info.yaml
            - type: url
              target: https://github.com/cdelashmutt-pivotal/appsso-starter-java/blob/main/catalog/catalog-info.yaml
        techdocs:
          builder: 'external'
          publisher:
            type: 'awsS3'
            awsS3:
              bucketName: 'cdd-demo-aws-techdocs'
              accountId: '537807987484'
              region: 'us-east-2'

        namespace_provisioner:
          default_parameters:
            supply_chain_service_account:
              secrets:
              - git-auth
        package_overlays:
        - name: tap-gui
          secrets:
          - name: tap-gui-overlay
          - name: tdp-app-image-overlay-secret
        - name: cert-manager
          secrets:
          - name: cert-manager-overlay
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tap
  namespace: tanzu-continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: tap
spec:
  serviceAccountName: tanzu-cd
  packageRef:
    refName: tap.roles.grogscave.net
    versionSelection:
      constraints: ">=1.0.0"
  values:
  - secretRef:
      name: tap-values
  - secretRef:
      name: tap-sensitive-values