apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tdp-configurator
  namespace: tdp
  labels:
    apps.tanzu.vmware.com/workload-type: tdp
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting tap"
    kapp.k14s.io/change-rule.1: "delete before deleting tap"
spec:
  build:
    env:
      - name: TPB_CONFIG_STRING
        value: IyB0ZHAtY29uZmlnLnlhbWwKCmFwcDoKICBwbHVnaW5zOgogICAgLSBuYW1lOiAnQHZtd2FyZS10YW56dS90ZHAtcGx1Z2luLXRlY2hpbnNpZ2h0cycKICAgICAgdmVyc2lvbjogJzAuMC4yJwogICAgLSBuYW1lOiAnQHZtd2FyZS10YW56dS90ZHAtcGx1Z2luLWhvbWUnCiAgICAgIHZlcnNpb246ICcwLjAuMicKICAgIC0gbmFtZTogJ0B2bXdhcmUtdGFuenUvdGRwLXBsdWdpbi1zdGFjay1vdmVyZmxvdycKICAgICAgdmVyc2lvbjogJzAuMC4yJwogICAgLSBuYW1lOiAnQHZtd2FyZS10YW56dS90ZHAtcGx1Z2luLXByb21ldGhldXMnCiAgICAgIHZlcnNpb246ICcwLjAuMicKICAgIC0gbmFtZTogJ0B2bXdhcmUtdGFuenUvdGRwLXBsdWdpbi1iYWNrc3RhZ2UtZ3JhZmFuYScKICAgICAgdmVyc2lvbjogJzAuMC4yJwpiYWNrZW5kOgogIHBsdWdpbnM6CiAgICAtIG5hbWU6ICdAdm13YXJlLXRhbnp1L3RkcC1wbHVnaW4tdGVjaGluc2lnaHRzLWJhY2tlbmQnCiAgICAgIHZlcnNpb246ICcwLjAuMicK