# tdp-config.yaml

app:
  plugins:
    - name: '@vmware-tanzu/tdp-plugin-techinsights'
      version: '0.0.2'
    - name: '@vmware-tanzu/tdp-plugin-home'
      version: '0.0.2'
    - name: '@vmware-tanzu/tdp-plugin-stack-overflow'
      version: '0.0.2'
    - name: '@vmware-tanzu/tdp-plugin-prometheus'
      version: '0.0.2'
    - name: '@vmware-tanzu/tdp-plugin-backstage-grafana'
      version: '0.0.2'
backend:
  plugins:
    - name: '@vmware-tanzu/tdp-plugin-techinsights-backend'
      version: '0.0.2'
