---
apiVersion: v1
kind: Secret
metadata:
  name: tap-values
  namespace: tanzu-continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: "tap-config"
    kapp.k14s.io/change-rule.0: "upsert before upserting tap"
    kapp.k14s.io/change-rule.1: "delete after deleting tap"
type: Opaque
stringData:
  values.yaml: |
    tap_install:
      version:
        package_repo_bundle_tag: "1.6.3"
        package_version: "1.6.3"
      values:
        shared:
          ingress_domain: "aws-work.grogscave.net"
          image_registry:
            project_path: "gcr.io/pa-cdelashmutt/cdd-demo-tap/supply-chain"
          kubernetes_version: "1.26"
        local_source_proxy:
          repository: gcr.io/pa-cdelashmutt/cdd-demo-tap/source
        contour:
          envoy:
            service:
              annotations:
                external-dns.alpha.kubernetes.io/hostname: '*.aws-work.grogscave.net'
        tap_gui:
          app_config:
            auth:
              environment: development
            customize:
              default_route: /home
            grafana:
              domain: https://grafana.aws-work.grogscave.net # URL of your Grafana domain
              unifiedAlerting: true

        namespace_provisioner:
          default_parameters:
            supply_chain_service_account:
              secrets:
              - git-auth
        package_overlays:
        - name: tap-gui
          secrets:
          - name: tap-gui-overlay
          - name: tdp-app-image-overlay-secret
        - name: cert-manager
          secrets:
          - name: cert-manager-overlay
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tap
  namespace: tanzu-continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: tap
spec:
  serviceAccountName: tanzu-cd
  packageRef:
    refName: tap.roles.grogscave.net
    versionSelection:
      constraints: ">=1.0.0"
  values:
  - secretRef:
      name: tap-values
  - secretRef:
      name: tap-sensitive-values