---
apiVersion: v1
kind: Secret
metadata:
  name: tap-values
  namespace: tanzu-continuousdelivery-resources
type: Opaque
stringData:
  values.yaml: |
    tap_install:
      version:
        package_repo_bundle_tag: ">=1.6.0 <1.7.0"
        package_version: ">=1.6.0 <1.7.0"
      package_repository:
        oci_repository: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages
      values:
        profile: full
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tap
  namespace: tanzu-continuousdelivery-resources
spec:
  serviceAccountName: tanzu-cd
  packageRef:
    refName: tap.roles.grogscave.net
    versionSelection:
      constraints: ">=1.0.0"
  values:
  - secretRef:
      name: tap-values
  - secretRef:
      name: tap-sensitive-values