---
apiVersion: v1
kind: Secret
metadata:
  name: tap-values
  namespace: tanzu-continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: "tap-config"
    kapp.k14s.io/change-rule.0: "upsert before upserting tap"
    kapp.k14s.io/change-rule.1: "delete after deleting tap"
type: Opaque
stringData:
  values.yaml: |
    tap_install:
      version:
        package_repo_bundle_tag: "1.7.0-rc.8"
        package_version: "1.7.0-rc.8"
      values:
        shared:
          ingress_domain: "aws-work.grogscave.net"
          image_registry:
            project_path: "gcr.io/pa-cdelashmutt/cdd-demo-tap/supply-chain"
          kubernetes_version: "1.27"
        local_source_proxy:
          repository: gcr.io/pa-cdelashmutt/cdd-demo-tap/source
        contour:
          envoy:
            service:
              annotations:
                external-dns.alpha.kubernetes.io/hostname: '*.aws-work.grogscave.net'
        tap_gui:
          app_config:
            auth:
              environment: development
        namespace_provisioner:
          default_parameters:
            supply_chain_service_account:
              secrets:
              - git-auth        
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tap
  namespace: tanzu-continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: tap
spec:
  serviceAccountName: tanzu-cd
  packageRef:
    refName: tap.roles.grogscave.net
    versionSelection:
      constraints: ">=1.0.0"
  values:
  - secretRef:
      name: tap-values
  - secretRef:
      name: tap-sensitive-values