apiVersion: v1
kind: Secret
metadata:
  name: external-dns-values
  namespace: tanzu-continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: "external-dns-config"
    kapp.k14s.io/change-rule.0: "upsert before upserting external-dns-pkgi"
    kapp.k14s.io/change-rule.1: "delete after deleting external-dns-pkgi"
type: Opaque
stringData:
  values.yaml: |
    domain: "aws-work.grogscave.net"
    owner_id: "cdd-demo-iterate"
    aws:
      role_arn: "arn:aws:iam::537807987484:role/cdd-demo-iterate-external-dns-external-dns"

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: external-dns
  namespace: tanzu-continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: "external-dns-pkgi"
    kapp.k14s.io/change-rule.0: "upsert before upserting tap"
    kapp.k14s.io/change-rule.1: "delete after deleting tap"
spec:
  serviceAccountName: tanzu-cd
  packageRef:
    refName: external-dns.roles.grogscave.net
    versionSelection:
      constraints: ">=1.0.0"
  values:
  - secretRef:
      name: external-dns-values