---
apiVersion: v1
kind: Secret
metadata:
  name: tap-values
  namespace: tanzu-continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: "tap-config"
    kapp.k14s.io/change-rule.0: "upsert before upserting tap"
    kapp.k14s.io/change-rule.1: "delete after deleting tap"
type: Opaque
stringData:
  values.yaml: |
    tap_install:
      version:
        package_repo_bundle_tag: "1.7.1"
        package_version: "1.7.1"
      values:
        profile: iterate
        shared:
          ingress_domain: "iterate.aws-work.grogscave.net"
          image_registry:
            project_path: "gcr.io/pa-cdelashmutt/cdd-demo-iterate"
            secret:
              name: registry-credentials
              namespace: tanzu-continuousdelivery-resources
          kubernetes_version: "1.27"
        supply_chain: basic
        contour:
          envoy:
            service:
              annotations:
                external-dns.alpha.kubernetes.io/hostname: '*.iterate.aws-work.grogscave.net'
        
        buildservice:
          kp_default_repository_secret:
            name: registry-credentials
            namespace: tanzu-continuousdelivery-resources


---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tap
  namespace: tanzu-continuousdelivery-resources
  annotations:
    kapp.k14s.io/change-group: tap
spec:
  serviceAccountName: tanzu-cd
  packageRef:
    refName: tap.roles.grogscave.net
    versionSelection:
      constraints: ">=1.0.0"
  values:
  - secretRef:
      name: tap-values
  - secretRef:
      name: tap-sensitive-values