---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting tap"
    kapp.k14s.io/change-rule.1: "delete before deleting tap"
  name: kp-default-repository-secret
  namespace: build-service
spec:
  toNamespaces:
  - "*"