apiVersion: v1
kind: Namespace
metadata:
  name: build-service
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: kp-default-repository-secret
  namespace: build-service
spec:
  toNamespaces:
  - "*"