#@ load("@ytt:data", "data")
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#! This if condition ensures that this git-auth import is only created if the supply chain is testing or testing_scanning, and the TAP profile used is full or build.
#@ if/end in_list('supply_chain', ['testing', 'testing_scanning']) and in_list('profile', ['full', 'build']):
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-auth
  annotations:
      tekton.dev/git-0: https://github.com
spec:
  fromNamespace: tanzu-continuousdelivery-resources