---
apiVersion: v1
kind: Namespace
metadata:
  name: tanzu-continuousdelivery-resources
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-cd
  namespace: tanzu-continuousdelivery-resources
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-cd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tanzu-cd
  namespace: tanzu-continuousdelivery-resources
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tmc-cd-bootstrap
  namespace: tanzu-continuousdelivery-resources
spec:
  serviceAccountName: tanzu-cd
  fetch:
  - inline:
      paths:
        eso.yaml: |
          ---
          apiVersion: source.toolkit.fluxcd.io/v1beta2
          kind: HelmRepository
          metadata:
            name: external-secrets
            namespace: tanzu-continuousdelivery-resources
          annotations:
            kapp.k14s.io/change-group: eso-hrepo
          spec:
            interval: 5m0s
            url: https://charts.external-secrets.io
          ---
          apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          metadata:
            name: external-secrets
            namespace: tanzu-continuousdelivery-resources
          annotations:
            kapp.k14s.io/change-group: eso-hrelease
            kapp.k14s.io/change-rule.0: "upsert after upserting eso-hrepo"
            kapp.k14s.io/change-rule.1: "delete before deleting eso-hrepo"
          spec:
            interval: 1m
            chart:
              spec:
                chart: external-secrets
                sourceRef:
                  kind: HelmRepository
                  name: external-secrets
                  namespace: tanzu-continuousdelivery-resources
                interval: 1m
                targetNamespace: external-secrets
            install:
              crds: CreateReplace
            upgrade:
              crds: CreateReplace
          ---
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/team-a
            name: eso-aws
            namespace: tanzu-continuousdelivery-resources
          ---
          apiVersion: external-secrets.io/v1beta1
          kind: SecretStore
          metadata:
            name: aws-secretsmanager
            namespace: tanzu-continuousdelivery-resources
          annotations:
            kapp.k14s.io/change-group: eso-secretstore
            kapp.k14s.io/change-rule.0: "upsert after upserting eso-hrelease"
            kapp.k14s.io/change-rule.1: "delete before deleting eso-hrelease"
          spec:
            provider:
              aws:
                service: SecretsManager
                region: us-east-2
                auth:
                  jwt:
                    serviceAccountRef:
                      name: eso-aws
          ---
          apiVersion: external-secrets.io/v1beta1
          kind: ExternalSecret
          metadata:
            name: age-key
            namespace: tanzu-continuousdelivery-resources
          annotations:
            kapp.k14s.io/change-group: eso-externalsecret
            kapp.k14s.io/change-rule.0: "upsert after upserting eso-secretstore"
            kapp.k14s.io/change-rule.1: "delete before deleting eso-secretstore"
          spec:
            refreshInterval: 1h
            secretStoreRef:
              name: aws-secretsmanager
              kind: SecretStore
            target:
              name: age-key
              creationPolicy: Owner
            data:
            - secretKey: key.txt
              remoteRef:
                key: "age-key"

        cluster-app.yaml: |
          #@ load("@ytt:data", "data")
          ---
          apiVersion: kappctrl.k14s.io/v1alpha1
          kind: App
          metadata:
            name: tmc-cd
            namespace: tanzu-continuousdelivery-resources
          annotations:
            kapp.k14s.io/change-rule.0: "upsert after upserting eso-externalsecret"
            kapp.k14s.io/change-rule.1: "delete before deleting eso-externalsecret"
          spec:
            serviceAccountName: tanzu-cd
            fetch:
            - git:
                url: https://github.com/cdelashmutt-pivotal/demo-clusters
                subPath: #@ "/clusters/" + data.values.cluster_name
                ref: origin/main
                lfsSkipSmudge: true
            template:
            - sops:
                age:
                  privateKeySecretRef:
                    name: age-key
            - ytt: {}
            - kbld: {}
            deploy:
            - kapp: {}
  template:
  - ytt:
      valuesFrom:
      - secretRef: 
          name: cluster-name-secret
  deploy:
  - kapp: {}
