apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-name-secret.yaml
- cd-resources.yaml
replacements:
- source:
    kind: Deployment
    fieldPath: metadata.name
  targets:
  - select:
      name: my-resource
