apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
replacements:
- source:
    kind: Deployment
    fieldPath: metadata.name
  targets:
  - select:
      name: my-resource
