apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: roles.grogscave.net
  namespace: tanzu-continuousdelivery-resources
spec:
  fetch:
    git:
      url: https://github.com/cdelashmutt-pivotal/demo-clusters
      ref: origin/main
      subPath: packagerepo/packages
      lfsSkipSmudge: true