apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/team-a
  name: eso-aws
  namespace: tanzu-continuousdelivery-resources
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: tanzu-continuousdelivery-resources
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: eso-aws
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: age-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: age-key
    creationPolicy: Owner
  data:
  - secretKey: key.txt
    remoteRef:
      key: "age-key"
